# Generated by Django 4.2.7 on 2023-12-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='category',
            field=models.CharField(choices=[('Horse health', 'Horse Health'), ('Horse riding', 'Horse Riding'), ('Buying horses', 'Buying Horses'), (' horse training', ' Horse Training'), ('General consultations', 'General Consultations')], default='', max_length=256),
        ),
    ]
