# Generated by Django 5.0 on 2023-12-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultations', '0003_consultationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='age_horse',
            field=models.IntegerField(default=0),
        ),
    ]
