# Generated by Django 5.0 on 2023-12-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Equipment', 'Equipment'), ('Houseware', 'Houseware'), ('Agriculture tools', 'Agriculture Tools'), ('Car tools', 'Car Tools'), ('Other', 'Other')], default='Other', max_length=64)),
                ('poster', models.ImageField(default='imgs/default.jpg', upload_to='imgs/')),
                ('reserved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
