# Generated by Django 5.0 on 2023-12-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='objective',
        ),
        migrations.AddField(
            model_name='order',
            name='objectives',
            field=models.ManyToManyField(to='objectives.objective'),
        ),
    ]
