# Generated by Django 5.0 on 2023-12-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0003_remove_order_objective_order_objectives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='objectives',
        ),
        migrations.AddField(
            model_name='order',
            name='objective',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='objectives.objective'),
            preserve_default=False,
        ),
    ]
