# Generated by Django 5.0 on 2023-12-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0005_objective_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='acceptance',
            field=models.BooleanField(default=0),
        ),
    ]
