# Generated by Django 4.2.7 on 2023-12-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0001_initial'),
        ('User', '0002_alter_profile_subreddit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subreddit',
            field=models.ManyToManyField(blank=True, to='subreddit.subreddit'),
        ),
    ]
