# Generated by Django 4.2.7 on 2023-12-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_profile_subreddit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.TextField(default='New_Redditor'),
        ),
    ]
