# Generated by Django 4.2.7 on 2023-12-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0003_alter_subreddit_author_alter_subreddit_description_and_more'),
        ('User', '0006_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subreddit',
            field=models.ManyToManyField(blank=True, default=0, to='subreddit.subreddit'),
        ),
    ]
