# Generated by Django 5.0 on 2023-12-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reservation_first_name_reservation_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seat_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
