# Generated by Django 5.0 on 2023-12-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_flight_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='flight',
            name='seat_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
