# Generated by Django 5.0 on 2023-12-12 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='main.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='main.city'),
            preserve_default=False,
        ),
    ]
