# Generated by Django 5.0 on 2023-12-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_flight_arrival_city_flight_departure_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='seat_number',
            field=models.IntegerField(null=True),
        ),
    ]
