# Generated by Django 4.2.7 on 2023-12-07 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('content', models.TextField()),
                ('published_at', models.DateField()),
                ('category', models.CharField(choices=[('brakfast', 'Brakfast'), ('brunch', 'Brunch'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('salad', 'Salad'), ('smoothie', 'Smoothie'), ('sweet', 'Sweet')], max_length=64)),
                ('rating', models.IntegerField()),
                ('picture', models.ImageField(default='img/default.jpg', upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('picture', models.ImageField(default='img/default.jpg', upload_to='img/')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
