# Generated by Django 4.2.7 on 2023-12-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='content',
            new_name='description',
        ),
    ]
