# Generated by Django 4.2.7 on 2023-12-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='published_at',
            field=models.DateField(auto_created=True),
        ),
    ]
