# Generated by Django 4.2.7 on 2023-12-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=-2023),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default='img/default.png', upload_to='img/'),
        ),
    ]
