# Generated by Django 4.2.7 on 2023-12-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_ingredients_alter_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='published_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
