# Generated by Django 4.2.7 on 2023-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparing',
            field=models.TextField(default=-2023),
            preserve_default=False,
        ),
    ]
