# Generated by Django 4.2.7 on 2023-12-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_preparing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='picture',
            new_name='image',
        ),
    ]
