# Generated by Django 4.2.7 on 2023-12-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_picture_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='img/default.png', upload_to='img/'),
        ),
    ]
