# Generated by Django 5.0 on 2023-12-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('salad', 'Salad'), ('smoothie', 'Smoothie'), ('sweet', 'Sweet')], default='sweet', max_length=64),
        ),
    ]
