# Generated by Django 4.2.7 on 2023-12-06 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subreddit', '0002_subreddit_author_alter_subreddit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='description',
            field=models.TextField(default='New Subreddit'),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='name',
            field=models.CharField(default='New Subreddit', max_length=255),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
