# Generated by Django 4.2.7 on 2023-12-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitall', '0002_anothermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnotherModel',
        ),
    ]
