# Generated by Django 4.2.7 on 2023-12-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitall', '0003_delete_anothermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinics',
            field=models.ManyToManyField(to='hospitall.clinic'),
        ),
    ]
