# Generated by Django 4.2.7 on 2023-12-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitall', '0004_remove_doctor_clinic_doctor_clinics'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='hospitall.clinic'),
            preserve_default=False,
        ),
    ]
