# Generated by Django 4.2.7 on 2023-12-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitall', '0006_clinic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='doctors/'),
        ),
    ]
