# Generated by Django 4.2.7 on 2023-12-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitall', '0007_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default='2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
