# Generated by Django 4.2.7 on 2023-12-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitall', '0008_doctor_experience_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cv',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
