# Generated by Django 5.0 on 2023-12-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_request_ordertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
