# Generated by Django 5.0 on 2023-12-12 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_request_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
