# Generated by Django 4.2.7 on 2023-12-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=2028)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('storage', 'Storage'), ('server', 'Server')], max_length=1024)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=1024)),
            ],
        ),
    ]
