# Generated by Django 4.2.7 on 2023-12-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('Simple Storage', 'Simple Storage'), ('Server', 'Server'), ('RestFullAPI', 'Restfullapi'), ('Mobile SDK', 'Mobile Sdk'), ('Monitor Clint', 'Monitor Clint'), ('Clint Endpoint', 'Clint Endpoint')], max_length=1024),
        ),
    ]
