# Generated by Django 4.2.7 on 2023-12-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_price_alter_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_endpoint', models.CharField(max_length=1024)),
                ('public_endpoint', models.CharField(max_length=1024)),
                ('private_ip', models.CharField(max_length=1024)),
                ('public_ip', models.CharField(max_length=1024)),
                ('elastic_ip', models.BooleanField(default=False)),
                ('platfrom', models.CharField(max_length=2024)),
                ('life_cycle', models.BooleanField(default=False)),
                ('high_availability', models.BooleanField(default=False)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
