# Generated by Django 4.2.7 on 2023-12-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='elastic_ip',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=False),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='high_availability',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=False),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='life_cycle',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=False),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='platfrom',
            field=models.CharField(choices=[('Linux', 'Linux'), ('Ububtu', 'Ububtu'), ('Windows', 'Windows'), ('Unix', 'Unix'), ('CloudLinux', 'Cloudlinux')], max_length=2024),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='private_endpoint',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='private_ip',
            field=models.CharField(choices=[('2.0.0.0', '2.0.0.0'), ('2.0.1.0', '2.0.1.0'), ('2.0.2.0', '2.0.2.0'), ('2.0.3.0', '2.0.3.0'), ('2.0.4.0', '2.0.4.0'), ('2.0.5.0', '2.0.5.0'), ('2.0.6.0', '2.0.6.0'), ('2.0.7.0', '2.0.7.0'), ('2.0.8.0', '2.0.8.0'), ('2.0.9.0', '2.0.9.0'), ('2.0.10.0', '2.0.10.0'), ('2.0.11.0', '2.0.11.0'), ('2.0.12.0', '2.0.12.0'), ('2.0.13.0', '2.0.13.0'), ('2.0.14.0', '2.0.14.0'), ('2.0.15.0', '2.0.15.0'), ('2.0.16.0', '2.0.16.0')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='public_endpoint',
            field=models.CharField(choices=[('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('800', '800'), ('900', '900'), ('1000', '1000'), ('1100', '1100'), ('1200', '1200'), ('1300', '1300'), ('1400', '1400'), ('1500', '1500'), ('1600', '1600'), ('1700', '1700'), ('1800', '1800'), ('1900', '1900'), ('2000', '2000'), ('2100', '2100'), ('2200', '2200')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='public_ip',
            field=models.CharField(choices=[('1.0.0.0', '1.0.0.0'), ('1.0.1.0', '1.0.1.0'), ('1.0.2.0', '1.0.2.0'), ('1.0.3.0', '1.0.3.0'), ('1.0.4.0', '1.0.4.0'), ('1.0.5.0', '1.0.5.0'), ('1.0.6.0', '1.0.6.0'), ('1.0.7.0', '1.0.7.0'), ('1.0.8.0', '1.0.8.0'), ('1.0.9.0', '1.0.9.0'), ('1.0.10.0', '1.0.10.0'), ('1.0.11.0', '1.0.11.0'), ('1.0.12.0', '1.0.12.0'), ('1.0.13.0', '1.0.13.0'), ('1.0.14.0', '1.0.14.0'), ('1.0.15.0', '1.0.15.0'), ('1.0.16.0', '1.0.16.0')], max_length=1024),
        ),
    ]
