# Generated by Django 4.2.7 on 2023-12-13 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0005_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2010-04-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicedetails',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
