# Generated by Django 4.2.7 on 2023-12-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicedetails_created_at_servicedetails_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('terminate', 'Terminate')], default='pending', max_length=10),
        ),
    ]
