# Generated by Django 5.0 on 2023-12-09 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("about", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Gynecology", "Gynecology"),
                            ("Dentistry", "Dentistry"),
                            ("Pediatric", "Pediatric"),
                            ("Psychiatry", "Psychiatry"),
                            ("Neurology", "Neurology"),
                            ("Dermatology", "Dermatology"),
                        ],
                        default="Coffee",
                        max_length=2048,
                    ),
                ),
                (
                    "image",
                    models.ImageField(default="image/default.jpg", upload_to="image/"),
                ),
                ("location", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=210)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=512)),
                ("rating", models.FloatField()),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.clinic"
                    ),
                ),
            ],
        ),
    ]
