# Generated by Django 5.0 on 2023-12-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="category",
            field=models.CharField(
                choices=[
                    ("Gynecology", "Gynecology"),
                    ("Dentistry", "Dentistry"),
                    ("Pediatric", "Pediatric"),
                    ("Psychiatry", "Psychiatry"),
                    ("Neurology", "Neurology"),
                    ("Dermatology", "Dermatology"),
                ],
                default="Coffee",
                max_length=2048,
            ),
        ),
    ]
