# Generated by Django 4.2.7 on 2023-12-06 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0001_initial'),
        ('User', '0003_alter_profile_subreddit'),
        ('Fourm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Subreddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subreddit.subreddit'),
        ),
        migrations.DeleteModel(
            name='Subreddit',
        ),
    ]
