# Generated by Django 4.2.7 on 2023-12-06 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subreddit', '0002_subreddit_author_alter_subreddit_slug'),
        ('Fourm', '0003_remove_post_subreddit_alter_comment_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='subreddit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subreddit.subreddit'),
        ),
    ]
