# Generated by Django 4.2.7 on 2023-12-06 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0002_subreddit_author_alter_subreddit_slug'),
        ('Fourm', '0004_alter_post_author_alter_post_subreddit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subreddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subreddit.subreddit'),
        ),
    ]
