# Generated by Django 4.2.7 on 2023-12-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fourm', '0007_comment_downvoters_comment_upvoters_post_downvoters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
