# Generated by Django 4.2.7 on 2023-12-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fourm', '0008_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isContentEdited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='whenContentEdited',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
