# Generated by Django 4.2.7 on 2023-12-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fourm', '0009_comment_iscontentedited_comment_whencontentedited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isContentEdited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='whenContentEdited',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
