# Generated by Django 4.2.7 on 2023-12-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('location', models.URLField(default='')),
                ('work_time', models.CharField(default='', max_length=256)),
                ('img', models.ImageField(default='images/default_store.jpg', upload_to='images/')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('img', models.ImageField(default='images/default_menu.jpg', upload_to='images/')),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default=0)),
                ('menu_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.store')),
            ],
        ),
    ]
