# Generated by Django 5.0 on 2023-12-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('location', models.URLField()),
                ('work_time', models.CharField(max_length=256)),
                ('img', models.ImageField(default='images/default_store.jpg', upload_to='images/')),
            ],
        ),
    ]
