# Generated by Django 5.0 on 2023-12-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rating',
            field=models.IntegerField(default=''),
        ),
    ]
