# Generated by Django 4.2.7 on 2023-12-10 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='store',
            name='work_time',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('img', models.ImageField(default='images/default_menu.jpg', upload_to='images/')),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default=0)),
                ('menu_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.store')),
            ],
        ),
    ]
