# Generated by Django 5.0 on 2023-12-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_store_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rating',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='store',
            name='work_time',
            field=models.CharField(default='', max_length=256),
        ),
    ]
