# Generated by Django 4.2.7 on 2023-12-09 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_store_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('img', models.ImageField(default='images/default_menu.jpg', upload_to='images/')),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default='')),
                ('menu_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.store')),
            ],
        ),
    ]
