# Generated by Django 5.0 on 2023-12-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_birth_date'),
        ('main', '0010_alter_flight_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reservations',
            field=models.ManyToManyField(blank=True, to='main.reservation'),
        ),
    ]
