# Generated by Django 5.0 on 2023-12-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expos', '0002_alter_news_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='poster',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
