# Generated by Django 5.0 on 2023-12-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expos', '0005_alter_news_publishd_at_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
