# Generated by Django 4.2.7 on 2023-12-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_join_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_link',
            new_name='insta_link',
        ),
    ]
