# Generated by Django 4.2.7 on 2023-12-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_email_link_profile_insta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitter_link',
            field=models.URLField(default='2023-09-10'),
            preserve_default=False,
        ),
    ]
