# Generated by Django 4.2.7 on 2023-12-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_twitter_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='twitter_link',
        ),
    ]
