# Generated by Django 5.0 on 2023-12-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Abayas', 'Abayas'), ('Dresses', 'Dresses'), ('Hoodies&Sweatshirts', 'Hoodies&Sweatshirts'), ('Jackets&Coats', 'Jackets&Coats'), ('Jeans', 'Jeans'), ('Tshirts&Vests', 'Tshirts&Vests')], max_length=200)),
                ('size', models.CharField(choices=[('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl'), ('XXL', 'Xxl')], max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
