# Generated by Django 4.2.7 on 2023-12-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StableHorses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('img', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
