# Generated by Django 4.2.7 on 2023-12-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablehorses',
            name='city',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='stablehorses',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stablehorses',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='stablehorses',
            name='rating',
            field=models.IntegerField(default=''),
        ),
    ]
