# Generated by Django 4.2.7 on 2023-12-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0002_stablehorses_city_alter_stablehorses_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesStable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Servic', models.CharField(max_length=256)),
                ('description_Servic', models.TextField()),
                ('duration_service', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
