# Generated by Django 5.0 on 2023-12-07 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0003_servicesstable'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesstable',
            name='stbleHorse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horses.stablehorses'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicesstable',
            name='description_Servic',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='servicesstable',
            name='duration_service',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='servicesstable',
            name='name_Servic',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='servicesstable',
            name='price',
            field=models.IntegerField(default=''),
        ),
    ]
