# Generated by Django 5.0 on 2023-12-12 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('horses', '0005_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='store_reviews',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.store'),
            preserve_default=False,
        ),
    ]
