# Generated by Django 5.0 on 2023-12-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0006_reviews_store_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='store_reviews',
        ),
    ]
