# Generated by Django 5.0 on 2023-12-12 12:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0008_servicerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceRequest',
            new_name='StableRequest',
        ),
    ]
