# Generated by Django 5.0 on 2023-12-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0009_rename_servicerequest_stablerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesstable',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stablehorses',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
