# Generated by Django 5.0 on 2023-12-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0010_alter_servicesstable_price_alter_stablehorses_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
