# Generated by Django 4.2.7 on 2023-12-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
        ('horses', '0011_alter_reviews_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesstable',
            name='request',
            field=models.ManyToManyField(to='request.stablerequest'),
        ),
        migrations.DeleteModel(
            name='StableRequest',
        ),
    ]
