# Generated by Django 4.2.7 on 2023-12-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2040)),
                ('description', models.TextField()),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Art', 'Art'), ('Fashion', 'Fashion'), ('Healthcare', 'Healthcare')], default='Art', max_length=80)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
