# Generated by Django 4.2.7 on 2023-12-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Art', 'Art'), ('Healthcare', 'Healthcare'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment')], max_length=100),
        ),
    ]
