# Generated by Django 4.2.7 on 2023-12-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='release_date',
        ),
        migrations.AddField(
            model_name='event',
            name='posting_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
