# Generated by Django 4.2.7 on 2023-12-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_ticket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
