# Generated by Django 4.2.7 on 2023-12-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_date',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=33),
            preserve_default=False,
        ),
    ]
