# Generated by Django 4.2.7 on 2023-12-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=1955),
            preserve_default=False,
        ),
    ]
