# Generated by Django 4.2.7 on 2023-12-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
