# Generated by Django 4.2.7 on 2023-12-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_event_start_date_event_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.CharField(max_length=2500),
        ),
    ]
