# Generated by Django 4.2.7 on 2023-12-13 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_remove_event_summary_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='last_date',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
