# Generated by Django 4.2.7 on 2023-12-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_ticket_last_date_remove_ticket_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='last_date',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
    ]
