# Generated by Django 4.2.7 on 2023-12-13 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_rename_last_date_event_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 13, 18, 47, 17, 240627, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
