# Generated by Django 4.2.7 on 2023-12-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_event_event_date_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=20200712),
            preserve_default=False,
        ),
    ]
