# Generated by Django 4.2.7 on 2023-12-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_remove_event_date_event_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='last_date',
            field=models.DateField(default=33),
            preserve_default=False,
        ),
    ]
