# Generated by Django 4.2.7 on 2023-12-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_remove_event_start_date_event_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='last_date',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=10),
            preserve_default=False,
        ),
    ]
