# Generated by Django 4.2.7 on 2023-12-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_remove_event_last_date_ticket_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date',
        ),
    ]
