# Generated by Django 4.2.7 on 2023-12-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_remove_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_date',
            field=models.DateField(default=111111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_date',
            field=models.DateField(default=33),
            preserve_default=False,
        ),
    ]
