# Generated by Django 4.2.7 on 2023-12-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_ticket_last_date_ticket_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='last_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
