# Generated by Django 5.0 on 2023-12-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('time', models.IntegerField()),
                ('Instructions', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('Breakfast-and-Brunch', 'Breakfast-And-Brunch'), ('Lunch', 'Lunch'), ('Healthy', 'Healthy'), ('Appetizers-and-Snacks', 'Appetizers-And-Snacks'), ('Salad', 'Salad'), ('SideDishes', 'Sidedishes'), ('Soups', 'Soups'), ('Bread', 'Bread'), ('Drinks', 'Drinks'), ('Desserts', 'Desserts')], max_length=300)),
            ],
        ),
    ]
