# Generated by Django 5.0 on 2023-12-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast&Brunch', 'Breakfast&Brunch'), ('Lunch', 'Lunch'), ('Healthy', 'Healthy'), ('Appetizers&Snacks', 'Appetizers&Snacks'), ('Salad', 'Salad'), ('SideDishes', 'Sidedishes'), ('Soups', 'Soups'), ('Bread', 'Bread'), ('Drinks', 'Drinks'), ('Desserts', 'Desserts')], max_length=300),
        ),
    ]
