# Generated by Django 5.0 on 2023-12-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Instructions',
            new_name='instructions',
        ),
    ]
