# Generated by Django 5.0 on 2023-12-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_instructions_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='kall',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
