# Generated by Django 4.2.7 on 2023-12-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast&Brunch', 'Breakfast&Brunch'), ('Lunch', 'Lunch'), ('Appetizers', 'Appetizers'), ('Salad', 'Salad'), ('Soups', 'Soups'), ('Bread', 'Bread'), ('Drinks', 'Drinks'), ('Desserts', 'Desserts')], max_length=300),
        ),
    ]
