# Generated by Django 5.0 on 2023-12-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_quantities_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='kall',
            new_name='cal',
        ),
    ]
