# Generated by Django 5.0 on 2023-12-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='brand',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
