# Generated by Django 5.0 on 2023-12-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_brand_ingredient_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='brand',
        ),
    ]
