# Generated by Django 5.0 on 2023-12-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[(1, 'Riyadh'), (2, 'Jeddah'), (3, 'Damamm')], default=1, max_length=64),
        ),
    ]
