# Generated by Django 5.0 on 2023-12-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("model", models.CharField(max_length=512)),
                ("year", models.PositiveIntegerField()),
                ("registration_number", models.CharField(max_length=20, unique=True)),
                ("color", models.CharField(max_length=20)),
                ("available", models.BooleanField(default=True)),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
