# Generated by Django 5.0 on 2023-12-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("contact_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="car",
            old_name="year",
            new_name="pags",
        ),
        migrations.RemoveField(
            model_name="car",
            name="daily_rate",
        ),
        migrations.RemoveField(
            model_name="car",
            name="registration_number",
        ),
        migrations.AddField(
            model_name="car",
            name="air_conditioner",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Standard"),
                    (2, "Climate Control"),
                    (3, "Dual-Zone Climate Control"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(default="", max_length=512),
        ),
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="seats",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="transmission_type",
            field=models.CharField(default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="car",
            name="name",
            field=models.CharField(default="", max_length=512),
        ),
        migrations.AddField(
            model_name="car",
            name="rental_company",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="car.rentalcompany",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(default="", max_length=100)),
                ("rating", models.PositiveIntegerField(default="")),
                ("comment", models.TextField(default="")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="car.car"
                    ),
                ),
            ],
        ),
    ]
