# Generated by Django 5.0 on 2023-12-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0003_rename_model_car_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.PositiveIntegerField(
                choices=[(1, "Diesel"), (2, "Petrol")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission_type",
            field=models.PositiveIntegerField(
                choices=[(1, "Automatic"), (2, "Manual")], default=1
            ),
        ),
    ]
