# Generated by Django 4.1.2 on 2023-12-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0005_remove_car_rental_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filtring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_class", models.CharField(default="", max_length=100)),
                ("vehicle_type", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
