# Generated by Django 4.1.2 on 2023-12-09 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("car", "0006_filtring"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="date_added",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="review",
            name="full_name",
        ),
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rental_pickup_location",
                    models.CharField(default="", max_length=512),
                ),
                (
                    "rental_return_location",
                    models.CharField(default="", max_length=512),
                ),
                ("rental_pickup_date", models.DateField()),
                ("rental_return_date", models.DateField()),
                ("rental_pickup_time", models.DateTimeField(auto_now_add=True)),
                ("rental_return_time", models.DateTimeField(auto_now_add=True)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="car.car"
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
