# Generated by Django 4.1.2 on 2023-12-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0007_rename_date_added_review_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rental",
            old_name="rental_pickup_time",
            new_name="rental_pickup_Datetime",
        ),
        migrations.RenameField(
            model_name="rental",
            old_name="rental_return_time",
            new_name="rental_return_Datetime",
        ),
        migrations.RemoveField(
            model_name="rental",
            name="rental_pickup_date",
        ),
        migrations.RemoveField(
            model_name="rental",
            name="rental_return_date",
        ),
        migrations.RemoveField(
            model_name="rental",
            name="total_cost",
        ),
        migrations.AddField(
            model_name="rental",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
