# Generated by Django 4.1.2 on 2023-12-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "car",
            "0008_rename_rental_pickup_time_rental_rental_pickup_datetime_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="city",
            field=models.CharField(
                choices=[("Riyadh", "Riyadh"), ("Khobar", "Khobar")],
                default="Riyadh",
                max_length=124,
            ),
        ),
    ]
