# Generated by Django 4.1.2 on 2023-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0010_alter_car_air_conditioner_alter_car_fuel_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="air_conditioner",
            field=models.TextField(
                choices=[
                    ("Standard", "Standard"),
                    ("Climate Control", "Climate Control"),
                    ("Dual-Zone Climate Control", "Dual-Zone Climate Control"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.TextField(
                choices=[("Diesel", "Diesel"), ("Petrol", "Petrol")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission_type",
            field=models.TextField(
                choices=[("Automatic", "Automatic"), ("Manual", "Manual")], default=1
            ),
        ),
    ]
