# Generated by Django 5.0 on 2023-12-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0012_alter_car_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="total_cost",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
