# Generated by Django 5.0 on 2023-12-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0013_rental_total_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="vehicle_class",
            field=models.TextField(
                choices=[
                    ("Economic", "Economic"),
                    ("Middle Class", "Middle Class"),
                    ("Top Grade", "Top Grade"),
                    ("Luxury", "Luxury"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="vehicle_type",
            field=models.TextField(
                choices=[("Sedan", "Sedan"), ("SUV", "SUV"), ("VAN", "VAN")], default=1
            ),
        ),
    ]
