# Generated by Django 5.0 on 2023-12-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0014_car_vehicle_class_car_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.PositiveIntegerField(
                choices=[(-200, -200), (-400, -400), (800, 800)], default=200
            ),
        ),
    ]
