# Generated by Django 4.1.2 on 2023-12-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0015_alter_car_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Filtring",
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=""),
        ),
    ]
