# Generated by Django 5.0 on 2023-12-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('address', models.CharField(max_length=2048)),
                ('image', models.ImageField(default='image/default.jpg', upload_to='image/')),
                ('about', models.TextField()),
                ('nationality', models.CharField(max_length=2048)),
                ('duration', models.CharField(max_length=2048)),
                ('quantity', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=2048)),
                ('category', models.CharField(choices=[('Electrician and Plumber ', 'Electrician And Plumber '), ('Clining', 'Clining'), ('Water filling', 'Water Filling'), ('Moving furniture', 'Moving Furniture')], max_length=2048)),
            ],
        ),
    ]
