# Generated by Django 5.0 on 2023-12-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='duration',
            field=models.CharField(choices=[('Electrician and Plumber ', 'Electrician And Plumber '), ('Clining', 'Clining'), ('Water filling', 'Water Filling'), ('Moving furniture', 'Moving Furniture')], max_length=2048),
        ),
    ]
