# Generated by Django 5.0 on 2023-12-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
