# Generated by Django 5.0 on 2023-12-11 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalhub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pfp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='evalhub.customuser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='performance_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
