# Generated by Django 5.0 on 2023-12-13 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalhub', '0002_remove_customuser_pfp_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_manager', to='evalhub.customuser'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Late', 'Late'), ('Progress', 'Progress'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m_employees', to='evalhub.customuser'),
        ),
    ]
