# Generated by Django 5.0 on 2023-12-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalhub', '0004_customuser_about_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
