# Generated by Django 5.0 on 2023-12-13 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalhub', '0005_alter_customuser_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employee_of',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='manager_of',
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evalhub.customuser'),
        ),
    ]
