# Generated by Django 5.0 on 2023-12-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('content', models.TextField()),
                ('size', models.IntegerField()),
                ('category', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Beige', 'Beige'), ('Brown', 'Brown'), ('Green', 'Green'), ('Blue', 'Blue')], default='Cultural', max_length=70)),
                ('choose_co', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
