# Generated by Django 5.0 on 2023-12-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_category_product_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='choose_co',
            new_name='choose_product',
        ),
    ]
