# Generated by Django 5.0 on 2023-12-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
