# Generated by Django 5.0 on 2023-12-13 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
