# Generated by Django 5.0 on 2023-12-07 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='rental',
            name='rent_from',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='rental',
            name='rent_to',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='sale',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
