# Generated by Django 5.0 on 2023-12-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_rental_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
