# Generated by Django 5.0 on 2023-12-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
