# Generated by Django 5.0 on 2023-12-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='image/default.pnd', upload_to='image/'),
        ),
    ]
